"""catalog schema

Revision ID: 2c775d0d0e64
Revises: 6d95e3289b27
Create Date: 2026-05-09 00:18:32.411971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c775d0d0e64'
down_revision: Union[str, Sequence[str], None] = '6d95e3289b27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalog_items',
    sa.Column('tmdb_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('media_type', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('original_title', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('poster_url', sa.Text(), nullable=True),
    sa.Column('backdrop_url', sa.Text(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('seasons_count', sa.Integer(), nullable=True),
    sa.Column('genres', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('metadata_fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("media_type IN ('movie', 'tv')", name='ck_catalog_items_media_type'),
    sa.PrimaryKeyConstraint('tmdb_id')
    )
    op.create_index(op.f('ix_catalog_items_year'), 'catalog_items', ['year'], unique=False)
    op.create_table('collections',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('media_type', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('refresh_ttl_hours', sa.Integer(), server_default='24', nullable=False),
    sa.Column('last_refreshed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalog_sources',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('service_short_name', sa.Text(), nullable=False),
    sa.Column('service_url', sa.Text(), nullable=False),
    sa.Column('service_media_id', sa.Text(), nullable=False),
    sa.Column('quality_max_height', sa.Integer(), nullable=True),
    sa.Column('languages_audio', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('languages_subs', sa.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('success_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('failure_count', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['tmdb_id'], ['catalog_items.tmdb_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tmdb_id', 'service_short_name')
    )
    op.create_index(op.f('ix_catalog_sources_service_short_name'), 'catalog_sources', ['service_short_name'], unique=False)
    op.create_table('collection_items',
    sa.Column('collection_id', sa.Text(), nullable=False),
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tmdb_id'], ['catalog_items.tmdb_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'tmdb_id')
    )
    op.create_table('tv_episodes',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('episode_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('overview', sa.Text(), nullable=True),
    sa.Column('air_date', sa.Date(), nullable=True),
    sa.Column('runtime_minutes', sa.Integer(), nullable=True),
    sa.Column('still_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tmdb_id'], ['catalog_items.tmdb_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tmdb_id', 'season_number', 'episode_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tv_episodes')
    op.drop_table('collection_items')
    op.drop_index(op.f('ix_catalog_sources_service_short_name'), table_name='catalog_sources')
    op.drop_table('catalog_sources')
    op.drop_table('collections')
    op.drop_index(op.f('ix_catalog_items_year'), table_name='catalog_items')
    op.drop_table('catalog_items')
    # ### end Alembic commands ###
