"""intro_markers

Revision ID: f4bac1844b73
Revises: ba0201dd461a
Create Date: 2026-05-09 14:40:11.691122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4bac1844b73'
down_revision: Union[str, Sequence[str], None] = 'ba0201dd461a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intro_markers',
    sa.Column('tmdb_id', sa.Integer(), nullable=False),
    sa.Column('season_number', sa.Integer(), nullable=False),
    sa.Column('intro_start_seconds', sa.Integer(), nullable=False),
    sa.Column('intro_end_seconds', sa.Integer(), nullable=False),
    sa.Column('outro_start_seconds', sa.Integer(), nullable=True),
    sa.Column('detected_by', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.CheckConstraint("detected_by IN ('fingerprint', 'manual')", name='ck_intro_markers_detected_by'),
    sa.ForeignKeyConstraint(['tmdb_id'], ['catalog_items.tmdb_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tmdb_id', 'season_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('intro_markers')
    # ### end Alembic commands ###
